// src/service-worker.js
import { precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies'

// Precache all the assets generated by CRA:
precacheAndRoute(self.__WB_MANIFEST)

// App shell for navigation—network first:
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'pages',
  })
)

// Static assets (CSS/JS/images)—stale while revalidate:
registerRoute(
  ({ request }) =>
    ['style', 'script', 'image'].includes(request.destination),
  new StaleWhileRevalidate({
    cacheName: 'assets',
  })
)